version: 2.1

machine:
  environment:
    ANDROID_HOME: "/usr/local/opt/android-sdk"
    ANDROID_SDK_HOME: "/usr/local/opt/android-sdk"
    ANDROID_SDK_ROOT: "/usr/local/opt/android-sdk"

dependencies:
  pre:
    - brew tap caskroom/cask
    - brew tap caskroom/versions
    - brew cask install android-sdk


jobs:
  build:
    macos:
      xcode: 14.2.0

    steps:
      - checkout
      - run:
          command: echo `which android`
      - run:
          name: Build and execute tests
          command: ./gradlew test
      - run:
          name: Upload code coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  gradle_test:
    jobs:
      - build
