version: 2.1



jobs:
  build:
    environment:
      ANDROID_HOME: "/usr/local/share/android-commandlinetools"
      ANDROID_SDK_HOME: "/usr/local/share/android-commandlinetools"
      ANDROID_SDK_ROOT: "/usr/local/share/android-commandlinetools"
      JAVA_HOME: "/usr"
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          command: |
            brew install android-commandlinetools
            brew remove android-sdk
            brew install --cask android-ndk
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "platforms;android-33"
      - run:
          name: Build and execute tests
          command: ./gradlew test
      - run:
          name: Upload code coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  gradle_test:
    jobs:
      - build
