version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  test-executor:
    docker:
      - image: cimg/openjdk:11.0.16

workflows:
  gradle_test:
    jobs:
      - gradle/test:
          executor: test-executor