version: 2.1

executors:
  test-executor:
    docker:
      - image: cimg/android:2022.09

jobs:
  build:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: Build and execute tests
          command: ./gradlew test
      - run:
          name: Upload code coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  gradle_test:
    jobs:
      - build
