[versions]
agp = "7.2.2"
androidxappcompat = "1.5.0"
androidxcore = "1.8.0"
androidxespressocore = "3.4.0"
androidxjunit = "1.1.3"
androidxtest = "1.4.0"
compose = "1.2.1"
coroutines = "1.6.4"
gson = "2.9.1"
junit = "4.13.2"
keccak = "1.1.1"
kluent = "1.68"
kotlin = "1.7.10"
material = "1.6.1"
mockk = "1.12.8"
retrofit = "2.9.0"
okhttp = "4.10.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxappcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxcore" }

androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxespressocore" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxjunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }

crypto-keccak = { module = "com.github.komputing.khash:keccak", version.ref = "keccak" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

material = { module = "com.google.android.material:material", version.ref = "material" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

test-fluent-assertions = { module = "org.amshove.kluent:kluent-android", version.ref = "kluent" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-mockk-agent = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }
